# Database config
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JWT Configuration
jwt.secret=${JWT_SECRET_KEY}
jwt.expiration=${JWT_EXPIRATION}

# Spring Doc
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

# Other configs
logging.level.root=warn
spring.main.banner-mode=off
logging.level.org.hibernate.SQL=trace
spring.jpa.hibernate.ddl-auto=none
spring.jackson.property-naming-strategy=SNAKE_CASE


